=head1 NAME

Gideon - ORM written in Perl

=head1 VERSION

alpha

=head1 SYNOPSIS

    use DBI;
    use Gideon;
    
    my $dbh = DBI->connect( "dbi:mysql:database=test;host=;port=", "test", "" );
    Gideon->register_store( 'mysql_server', $dbh );

    or
    
    Gideon->register_store( 'mysql_server', MyApp::Driver::MySQL->new(
        db       => 'test',
        username => 'test',
        host     => 'localhost'
    ));
    
    then
    
    my $results = MyApp::Persons->find_all( name => { like => 'Doe' } );

=head1 DESCRIPTION

Yet to come ...

=head1 SUPPORT

=head2 Bugs / Feature Requests

Don't try to use Gideon just yet, is not even an alpha version

Its purpose is to provide persistence using Moose-type objects without 
worrying about storage format.
Goal is to store objects without changing their class definitions, 
no schemas required just plain Perl classes with Mouse::Meta::Attribute::Custom 
extensions. It doesn't provide joins between two objects right now.

=head1 LIMITATIONS

CURRENT ENGINES SUPPORTED

=over 2

=item *

DBI

=over 2

=item *
MySQL

=item *
SQLIte

=back
 
=item *
Storable (veeery basic)

=item *
MongoDB

=back

=head1 DEPENDENCIES

=over 4

=item *
Mouse

=item *
Try::Tiny

=item *
Set::Array

=item *
DBI

=item *
SQL::Abstract

=item *
Test::Exception

=item *
Test::More

=item *
Data::Dumper

=back

=head2 Source Code

This is open source software.  The code repository is available for
public review and contribution under the terms of the license.

L<https://github.com/ginesr/Gideon>

  git clone https://github.com/ginesr/Gideon.git

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Gines Razanov.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.
